spring.application.name: SpringBootAPI
server.port: 8080
cloud:
    gateway:
        routes:
            - id: user-service
              uri: https://localhost:8081
              predicates:
                - Path=/user-service/**
              filters:
                - RewritePath=/user-service/(?<segment>.*),$\{segment}
            - id: order-service
              uri: https://localhost:8082
              predicates:
                - Path=/order-service/**
              filters:
                - RewritePath=/order-service/(?<segment>.*),$\{segment}